import { env } from "cloudflare:workers";
import { atlasV2Seed } from "../../../lib/atlas-v2-data";

export const dynamic = "force-dynamic";

type ProductAnalysis = {
  summary: string; valueProposition: string; icp: string; pains: string[]; useCases: string[]; competitors: string[]; channels: string[]; nextBestActions: { title: string; description: string; expectedOutcome: string }[]; opportunities: { title: string; summary: string; suggestedAction: string; signal: string; confidence: number }[];
};

const defaultWorkspaceId = "demo-workspace";
const defaultUserId = "demo-user";
const nowText = () => new Date().toISOString();

const tables = [
  `CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, email TEXT, name TEXT, locale TEXT NOT NULL DEFAULT 'zh', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS workspaces (id TEXT PRIMARY KEY, name TEXT NOT NULL, created_by_user_id TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS workspace_members (workspace_id TEXT NOT NULL, user_id TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'owner', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (workspace_id, user_id))`,
  `CREATE TABLE IF NOT EXISTS products (id INTEGER PRIMARY KEY AUTOINCREMENT, workspace_id TEXT NOT NULL, name TEXT NOT NULL, url TEXT NOT NULL, description TEXT, growth_goal TEXT, analysis_status TEXT NOT NULL DEFAULT 'pending', analysis_error TEXT, analysis_json TEXT, fetched_title TEXT, fetched_description TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS agents (id INTEGER PRIMARY KEY, workspace_id TEXT NOT NULL DEFAULT '${defaultWorkspaceId}', name TEXT NOT NULL, role TEXT NOT NULL, description TEXT NOT NULL, status TEXT NOT NULL, autonomy_level INTEGER NOT NULL, schedule TEXT NOT NULL, success_rate INTEGER NOT NULL, current_task TEXT NOT NULL, tools TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS agent_tasks (id INTEGER PRIMARY KEY, workspace_id TEXT NOT NULL DEFAULT '${defaultWorkspaceId}', agent_id INTEGER NOT NULL, title TEXT NOT NULL, description TEXT NOT NULL, task_type TEXT NOT NULL, priority INTEGER NOT NULL, risk_level INTEGER NOT NULL, status TEXT NOT NULL, requires_approval INTEGER NOT NULL DEFAULT 0, expected_outcome TEXT NOT NULL, estimated_minutes INTEGER NOT NULL, evidence TEXT NOT NULL, created_at TEXT NOT NULL, started_at TEXT, completed_at TEXT)`,
  `CREATE TABLE IF NOT EXISTS agent_runs (id INTEGER PRIMARY KEY, workspace_id TEXT NOT NULL DEFAULT '${defaultWorkspaceId}', agent_id INTEGER NOT NULL, task_id INTEGER, task TEXT NOT NULL, status TEXT NOT NULL, input TEXT NOT NULL, output TEXT NOT NULL, tools TEXT NOT NULL, started_at TEXT NOT NULL, finished_at TEXT, result TEXT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS approvals (id INTEGER PRIMARY KEY, workspace_id TEXT NOT NULL DEFAULT '${defaultWorkspaceId}', task_id INTEGER NOT NULL, action_type TEXT NOT NULL, title TEXT NOT NULL, reason TEXT NOT NULL, payload TEXT NOT NULL, risk_level INTEGER NOT NULL, status TEXT NOT NULL, created_at TEXT NOT NULL, approved_by TEXT, approved_at TEXT, expires_at TEXT)`,
  `CREATE TABLE IF NOT EXISTS memories (id INTEGER PRIMARY KEY, workspace_id TEXT NOT NULL DEFAULT '${defaultWorkspaceId}', memory_type TEXT NOT NULL, title TEXT NOT NULL, content TEXT NOT NULL, source TEXT NOT NULL, confidence INTEGER NOT NULL, status TEXT NOT NULL, last_verified_at TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS observations (id INTEGER PRIMARY KEY AUTOINCREMENT, workspace_id TEXT NOT NULL DEFAULT '${defaultWorkspaceId}', source_type TEXT NOT NULL, source_name TEXT NOT NULL, content TEXT NOT NULL, raw_data TEXT, observed_at TEXT NOT NULL, processed INTEGER NOT NULL DEFAULT 0)`,
  `CREATE TABLE IF NOT EXISTS opportunities (id INTEGER PRIMARY KEY, workspace_id TEXT NOT NULL DEFAULT '${defaultWorkspaceId}', title TEXT NOT NULL, source TEXT NOT NULL, observed_at TEXT NOT NULL, confidence INTEGER NOT NULL, summary TEXT NOT NULL, suggested_action TEXT NOT NULL, status TEXT NOT NULL, signal TEXT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS connections (id INTEGER PRIMARY KEY, workspace_id TEXT NOT NULL DEFAULT '${defaultWorkspaceId}', name TEXT NOT NULL, description TEXT NOT NULL, status TEXT NOT NULL, last_sync TEXT NOT NULL, category TEXT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS metrics (id INTEGER PRIMARY KEY AUTOINCREMENT, workspace_id TEXT NOT NULL DEFAULT '${defaultWorkspaceId}', metric_date TEXT NOT NULL, visits INTEGER NOT NULL, signups INTEGER NOT NULL, paid INTEGER NOT NULL, conversion REAL NOT NULL, completed_tasks INTEGER NOT NULL)`,
];
const workspaceTables = ["agents","agent_tasks","agent_runs","approvals","memories","observations","opportunities","connections","metrics"];
async function addWorkspaceColumns(db: D1Database) { for (const table of workspaceTables) { try { await db.prepare(`ALTER TABLE ${table} ADD COLUMN workspace_id TEXT NOT NULL DEFAULT '${defaultWorkspaceId}'`).run(); } catch {} } }
async function ensureSeed() { const db = env.DB; await db.batch(tables.map((s) => db.prepare(s))); await addWorkspaceColumns(db); await db.prepare("INSERT OR IGNORE INTO users (id, email, name) VALUES (?, ?, ?)").bind(defaultUserId, "demo@lumeword.com", "Demo Founder").run(); await db.prepare("INSERT OR IGNORE INTO workspaces (id, name, created_by_user_id) VALUES (?, ?, ?)").bind(defaultWorkspaceId, "LumeWord", defaultUserId).run(); await db.prepare("INSERT OR IGNORE INTO workspace_members (workspace_id, user_id, role) VALUES (?, ?, ?)").bind(defaultWorkspaceId, defaultUserId, "owner").run(); const count = await db.prepare("SELECT COUNT(*) AS count FROM agents WHERE workspace_id = ?").bind(defaultWorkspaceId).first<{ count: number }>(); if ((count?.count ?? 0) > 0) return; const statements = [
...atlasV2Seed.agents.map((i) => db.prepare("INSERT INTO agents (id, workspace_id, name, role, description, status, autonomy_level, schedule, success_rate, current_task, tools) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)").bind(i.id, defaultWorkspaceId, i.name, i.role, i.description, i.status, i.autonomyLevel, i.schedule, i.successRate, i.currentTask, JSON.stringify(i.tools))),
...atlasV2Seed.tasks.map((i) => db.prepare("INSERT INTO agent_tasks (id, workspace_id, agent_id, title, description, task_type, priority, risk_level, status, requires_approval, expected_outcome, estimated_minutes, evidence, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)").bind(i.id, defaultWorkspaceId, i.agentId, i.title, i.description, i.taskType, i.priority, i.riskLevel, i.status, Number(i.requiresApproval), i.expectedOutcome, i.estimatedMinutes, JSON.stringify(i.evidence), i.createdAt)),
...atlasV2Seed.approvals.map((i) => db.prepare("INSERT INTO approvals (id, workspace_id, task_id, action_type, title, reason, payload, risk_level, status, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)").bind(i.id, defaultWorkspaceId, i.taskId, i.actionType, i.title, i.reason, i.payload, i.riskLevel, i.status, i.createdAt)),
...atlasV2Seed.runs.map((i) => db.prepare("INSERT INTO agent_runs (id, workspace_id, agent_id, task_id, task, status, input, output, tools, started_at, finished_at, result) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)").bind(i.id, defaultWorkspaceId, i.agentId, i.taskId, i.task, i.status, i.input, i.output, JSON.stringify(i.tools), i.startedAt, i.finishedAt, i.result)),
...atlasV2Seed.opportunities.map((i) => db.prepare("INSERT INTO opportunities (id, workspace_id, title, source, observed_at, confidence, summary, suggested_action, status, signal) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)").bind(i.id, defaultWorkspaceId, i.title, i.source, i.observedAt, i.confidence, i.summary, i.suggestedAction, i.status, i.signal)),
...atlasV2Seed.memories.map((i) => db.prepare("INSERT INTO memories (id, workspace_id, memory_type, title, content, source, confidence, status, last_verified_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)").bind(i.id, defaultWorkspaceId, i.type, i.title, i.content, i.source, i.confidence, i.status, i.verifiedAt)),
...atlasV2Seed.connections.map((i) => db.prepare("INSERT INTO connections (id, workspace_id, name, description, status, last_sync, category) VALUES (?, ?, ?, ?, ?, ?, ?)").bind(i.id, defaultWorkspaceId, i.name, i.description, i.status, i.lastSync, i.category)), db.prepare("INSERT INTO metrics (workspace_id, metric_date, visits, signups, paid, conversion, completed_tasks) VALUES (?, ?, ?, ?, ?, ?, ?)").bind(defaultWorkspaceId, "2026-07-14", 0, 0, 0, 0, 0)]; await db.batch(statements); }
function parse<T>(value: unknown, fallback: T): T { if (typeof value !== "string") return fallback; try { return JSON.parse(value) as T; } catch { return fallback; } }
async function requireWorkspace(request: Request) { const db = env.DB; const userId = request.headers.get("x-atlas-user-id") || defaultUserId; const workspaceId = request.headers.get("x-atlas-workspace-id") || defaultWorkspaceId; const member = await db.prepare("SELECT role FROM workspace_members WHERE user_id = ? AND workspace_id = ?").bind(userId, workspaceId).first(); if (!member) throw new Response(JSON.stringify({ error: "Workspace access denied" }), { status: 403 }); return workspaceId; }
async function snapshot(workspaceId: string) { const db = env.DB; const [product, agents, tasks, approvals, runs, opportunities, memories, connections, metrics] = await Promise.all([
 db.prepare("SELECT id, name, url, description, growth_goal AS growthGoal, analysis_status AS analysisStatus, analysis_error AS analysisError, analysis_json AS analysisJson FROM products WHERE workspace_id = ? ORDER BY id DESC LIMIT 1").bind(workspaceId).first(),
 db.prepare("SELECT id, name, role, description, status, autonomy_level AS autonomyLevel, schedule, success_rate AS successRate, current_task AS currentTask, tools FROM agents WHERE workspace_id = ? ORDER BY id").bind(workspaceId).all(),
 db.prepare("SELECT id, agent_id AS agentId, title, description, task_type AS taskType, priority, risk_level AS riskLevel, status, requires_approval AS requiresApproval, expected_outcome AS expectedOutcome, estimated_minutes AS estimatedMinutes, evidence, created_at AS createdAt FROM agent_tasks WHERE workspace_id = ? ORDER BY priority, id DESC LIMIT 20").bind(workspaceId).all(),
 db.prepare("SELECT id, task_id AS taskId, action_type AS actionType, title, reason, payload, risk_level AS riskLevel, status, created_at AS createdAt FROM approvals WHERE workspace_id = ? ORDER BY id").bind(workspaceId).all(),
 db.prepare("SELECT id, agent_id AS agentId, task_id AS taskId, task, status, input, output, tools, started_at AS startedAt, finished_at AS finishedAt, result FROM agent_runs WHERE workspace_id = ? ORDER BY id DESC").bind(workspaceId).all(),
 db.prepare("SELECT id, title, source, observed_at AS observedAt, confidence, summary, suggested_action AS suggestedAction, status, signal FROM opportunities WHERE workspace_id = ? ORDER BY id DESC").bind(workspaceId).all(),
 db.prepare("SELECT id, memory_type AS type, title, content, source, confidence, status, last_verified_at AS verifiedAt FROM memories WHERE workspace_id = ? ORDER BY id DESC").bind(workspaceId).all(),
 db.prepare("SELECT id, name, description, status, last_sync AS lastSync, category FROM connections WHERE workspace_id = ? ORDER BY id").bind(workspaceId).all(),
 db.prepare("SELECT visits, signups, paid, conversion, completed_tasks AS completedTasks FROM metrics WHERE workspace_id = ? ORDER BY id DESC LIMIT 1").bind(workspaceId).first(),]); return { workspace: { id: workspaceId }, product: product ? { ...product, analysis: parse((product as { analysisJson?: string }).analysisJson, null) } : null, agents: agents.results.map((i) => ({...i, tools: parse(i.tools, [])})), tasks: tasks.results.map((i) => ({...i, requiresApproval: Boolean(i.requiresApproval), evidence: parse(i.evidence, [])})), approvals: approvals.results, runs: runs.results.map((i) => ({...i, tools: parse(i.tools, [])})), opportunities: opportunities.results, memories: memories.results, connections: connections.results, metrics: { ...(metrics ?? { visits: 0, signups: 0, paid: 0, conversion: 0, completedTasks: 0 }), yesterdayCompleted: (metrics as { completedTasks?: number } | null)?.completedTasks ?? 0 } }; }
function isPrivateHost(hostname: string) { const host = hostname.toLowerCase().replace(/^\[|\]$/g, ""); if (["localhost", "0.0.0.0"].includes(host) || host.endsWith(".local") || host.endsWith(".internal")) return true; const parts = host.split(".").map(Number); if (parts.length === 4 && parts.every((n) => Number.isInteger(n) && n >= 0 && n <= 255)) { const [a,b] = parts; return a === 10 || a === 127 || a === 0 || (a === 172 && b >= 16 && b <= 31) || (a === 192 && b === 168) || (a === 169 && b === 254); } if (host === "::1" || host.startsWith("fc") || host.startsWith("fd") || host.startsWith("fe80")) return true; return false; }
function validateUrl(input: string) { const url = new URL(input); if (!["http:", "https:"].includes(url.protocol) || isPrivateHost(url.hostname)) throw new Error("Only public http/https URLs are allowed."); return url; }
async function fetchPublicPage(input: string) { let url = validateUrl(input); for (let i=0;i<4;i++) { const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), 10000); const response = await fetch(url.toString(), { redirect: "manual", signal: controller.signal, headers: { "user-agent": "AtlasProductAnalysisBot/1.0" } }); clearTimeout(timeout); if ([301,302,303,307,308].includes(response.status)) { const location = response.headers.get("location"); if (!location) throw new Error("Redirect without Location header."); url = validateUrl(new URL(location, url).toString()); continue; } const type = response.headers.get("content-type") || ""; if (!response.ok || !type.includes("text/html")) throw new Error("URL must return a public HTML page."); const text = await response.text(); const html = text.slice(0, 750_000); const title = (html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1] || "").replace(/\s+/g, " ").trim(); const description = (html.match(/<meta[^>]+name=["']description["'][^>]+content=["']([^"']+)/i)?.[1] || "").trim(); const body = html.replace(/<script[\s\S]*?<\/script>/gi, " ").replace(/<style[\s\S]*?<\/style>/gi, " ").replace(/<[^>]+>/g, " ").replace(/&nbsp;|&#160;/g, " ").replace(/\s+/g, " ").trim().slice(0, 12000); return { finalUrl: url.toString(), title, description, body }; } throw new Error("Too many redirects."); }
async function analyzeProduct(product: { name: string; url: string; description?: string; growthGoal?: string }, page: { title: string; description: string; body: string }) { const key = env.OPENAI_API_KEY || env.LLM_API_KEY; if (!key) throw new Error("Missing server LLM key. Set OPENAI_API_KEY or LLM_API_KEY in the Cloudflare environment."); const prompt = `Analyze this product website. Return strict JSON with keys summary,valueProposition,icp,pains,useCases,competitors,channels,nextBestActions,opportunities. Product: ${JSON.stringify(product)} Page: ${JSON.stringify(page)}`; const res = await fetch("https://api.openai.com/v1/chat/completions", { method: "POST", headers: { authorization: `Bearer ${key}`, "content-type": "application/json" }, body: JSON.stringify({ model: env.OPENAI_MODEL || "gpt-4o-mini", response_format: { type: "json_object" }, messages: [{ role: "system", content: "You are a growth strategy analyst. Return concise JSON only. nextBestActions has 3 objects with title, description, expectedOutcome. opportunities has 3 objects." }, { role: "user", content: prompt }] }) }); if (!res.ok) throw new Error(`LLM request failed: ${await res.text()}`); const json = await res.json() as { choices?: { message?: { content?: string } }[] }; return JSON.parse(json.choices?.[0]?.message?.content || "{}") as ProductAnalysis; }
async function runAnalysis(workspaceId: string, input: { name: string; url: string; description?: string; growthGoal?: string }) { const db = env.DB; const started = nowText(); const task = await db.prepare("INSERT INTO agent_tasks (workspace_id, agent_id, title, description, task_type, priority, risk_level, status, requires_approval, expected_outcome, estimated_minutes, evidence, created_at, started_at) VALUES (?, 1, ?, ?, 'product_analysis', 1, 1, 'running', 0, ?, 3, ?, ?, ?) RETURNING id").bind(workspaceId, `Analyze ${input.name}`, `Fetch and analyze ${input.url}`, "Create product memory and next best actions", JSON.stringify([input.url]), started, started).first<{ id: number }>(); const run = await db.prepare("INSERT INTO agent_runs (workspace_id, agent_id, task_id, task, status, input, output, tools, started_at, result) VALUES (?, 1, ?, 'Product Analysis Agent', 'running', ?, 'Fetching public website', ?, ?, 'Running') RETURNING id").bind(workspaceId, task?.id ?? null, input.url, JSON.stringify(["SafeFetchWebsiteTool", "LLMAnalyzeProductTool", "SaveWorkspaceMemoryTool"]), started).first<{ id: number }>(); const product = await db.prepare("INSERT INTO products (workspace_id, name, url, description, growth_goal, analysis_status) VALUES (?, ?, ?, ?, ?, 'running') RETURNING id").bind(workspaceId, input.name, input.url, input.description || null, input.growthGoal || null).first<{ id: number }>(); try { const page = await fetchPublicPage(input.url); const analysis = await analyzeProduct(input, page); const finished = nowText(); await db.batch([
 db.prepare("UPDATE products SET url = ?, fetched_title = ?, fetched_description = ?, analysis_status = 'completed', analysis_json = ?, updated_at = ? WHERE id = ? AND workspace_id = ?").bind(page.finalUrl, page.title, page.description, JSON.stringify(analysis), finished, product?.id, workspaceId),
 db.prepare("INSERT INTO observations (workspace_id, source_type, source_name, content, raw_data, observed_at, processed) VALUES (?, 'website', ?, ?, ?, ?, 1)").bind(workspaceId, page.finalUrl, page.title || page.description || page.body.slice(0, 500), JSON.stringify(page), finished),
 db.prepare("INSERT INTO memories (workspace_id, memory_type, title, content, source, confidence, status, last_verified_at) VALUES (?, 'Product', ?, ?, ?, 88, 'validated', ?)").bind(workspaceId, `Product summary: ${input.name}`, `${analysis.summary}\n\nValue proposition: ${analysis.valueProposition}`, page.finalUrl, finished),
 db.prepare("INSERT INTO memories (workspace_id, memory_type, title, content, source, confidence, status, last_verified_at) VALUES (?, 'ICP', ?, ?, ?, 82, 'validated', ?)").bind(workspaceId, `ICP for ${input.name}`, analysis.icp, "Product Analysis Agent", finished),
 ...analysis.nextBestActions.slice(0,3).map((a, idx) => db.prepare("INSERT INTO agent_tasks (workspace_id, agent_id, title, description, task_type, priority, risk_level, status, requires_approval, expected_outcome, estimated_minutes, evidence, created_at, completed_at) VALUES (?, 1, ?, ?, 'next_best_action', ?, 1, 'queued', 0, ?, 30, ?, ?, ?)").bind(workspaceId, a.title, a.description, idx+1, a.expectedOutcome, JSON.stringify(["Product Analysis Agent", page.finalUrl]), finished, finished)),
 ...analysis.opportunities.slice(0,3).map((o) => db.prepare("INSERT INTO opportunities (workspace_id, title, source, observed_at, confidence, summary, suggested_action, status, signal) VALUES (?, ?, 'Product Analysis Agent', ?, ?, ?, ?, 'new', ?)").bind(workspaceId, o.title, finished, o.confidence, o.summary, o.suggestedAction, o.signal)),
 db.prepare("UPDATE agent_tasks SET status = 'completed', completed_at = ? WHERE id = ? AND workspace_id = ?").bind(finished, task?.id, workspaceId),
 db.prepare("UPDATE agent_runs SET status = 'completed', output = ?, finished_at = ?, result = 'Success · Workspace updated' WHERE id = ? AND workspace_id = ?").bind(`Generated ${analysis.nextBestActions.length} actions and ${analysis.opportunities.length} opportunities.`, finished, run?.id, workspaceId),
 ]); } catch (error) { const message = error instanceof Error ? error.message : "Analysis failed"; await db.batch([db.prepare("UPDATE products SET analysis_status = 'failed', analysis_error = ? WHERE id = ? AND workspace_id = ?").bind(message, product?.id, workspaceId), db.prepare("UPDATE agent_tasks SET status = 'failed', completed_at = ? WHERE id = ? AND workspace_id = ?").bind(nowText(), task?.id, workspaceId), db.prepare("UPDATE agent_runs SET status = 'failed', output = ?, finished_at = ?, result = 'Failed' WHERE id = ? AND workspace_id = ?").bind(message, nowText(), run?.id, workspaceId)]); throw error; } }
export async function GET(request: Request) { await ensureSeed(); const workspaceId = await requireWorkspace(request); return Response.json(await snapshot(workspaceId)); }
export async function POST(request: Request) { await ensureSeed(); const workspaceId = await requireWorkspace(request); const body = await request.json() as { action?: string; id?: number; product?: { name?: string; url?: string; description?: string; growthGoal?: string } }; const db = env.DB; if (body.action === "onboard") { if (!body.product?.name || !body.product?.url) return Response.json({ error: "Product name and URL are required." }, { status: 400 }); try { validateUrl(body.product.url); await runAnalysis(workspaceId, { name: body.product.name, url: body.product.url, description: body.product.description, growthGoal: body.product.growthGoal }); return Response.json(await snapshot(workspaceId)); } catch (error) { return Response.json({ error: error instanceof Error ? error.message : "Analysis failed" }, { status: 400 }); } }
 if (!body.id || !["approve", "reject", "defer", "save_opportunity", "ignore_opportunity"].includes(body.action ?? "")) return Response.json({ error: "Invalid action" }, { status: 400 }); if (body.action === "approve" || body.action === "reject" || body.action === "defer") { const status = body.action === "approve" ? "approved" : body.action === "reject" ? "rejected" : "deferred"; const approval = await db.prepare("SELECT task_id AS taskId FROM approvals WHERE id = ? AND workspace_id = ?").bind(body.id, workspaceId).first<{ taskId: number }>(); await db.batch([db.prepare("UPDATE approvals SET status = ?, approved_by = ?, approved_at = ? WHERE id = ? AND workspace_id = ?").bind(status, "Founder", "刚刚", body.id, workspaceId), ...(approval ? [db.prepare("UPDATE agent_tasks SET status = ? WHERE id = ? AND workspace_id = ?").bind(status === "approved" ? "approved" : status, approval.taskId, workspaceId)] : [])]); } else { await db.prepare("UPDATE opportunities SET status = ? WHERE id = ? AND workspace_id = ?").bind(body.action === "save_opportunity" ? "saved" : "ignored", body.id, workspaceId).run(); } return Response.json(await snapshot(workspaceId)); }
