"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";

export function AtlasLogin({ returnTo, initialError }: { returnTo: string; initialError: string }) {
  const [email, setEmail] = useState(""); const [busy, setBusy] = useState(false); const [sent, setSent] = useState(false); const [error, setError] = useState(initialError ? "登录链接无效、已过期或登录服务尚未配置。" : "");
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(""); try { const response = await fetch("/api/auth/email/start", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ email, returnTo }) }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.error || "邮件发送失败，请稍后重试。"); setSent(true); } catch (cause) { setError(cause instanceof Error ? cause.message : "邮件发送失败，请稍后重试。"); } finally { setBusy(false); } };
  return <main className="atlas-login-shell"><section className="atlas-login-story"><Link href="/" className="atlas-login-brand"><span>▲</span><div><strong>ATLAS</strong><small>LUMEWORD AI WORKSPACE</small></div></Link><div><p>YOUR FIRST AI EMPLOYEE</p><h1>每天理解增长，<br />每天执行下一步。</h1><span>连接产品、渠道与真实数据，让 Atlas 持续观察、复盘并准备增长工作。</span></div><footer>OBSERVE · PLAN · EXECUTE · MEASURE · REFLECT</footer></section><section className="atlas-login-panel"><div className="atlas-login-card"><p>WELCOME TO ATLAS</p><h2>登录或创建账户</h2><span>首次使用邮箱或 Google 登录时会自动创建账户。</span><a className="login-provider google" href={`/api/auth/google/start?return_to=${encodeURIComponent(returnTo)}`}><b>G</b> 使用 Google 继续</a><a className="login-provider chatgpt" href={`/signin-with-chatgpt?return_to=${encodeURIComponent(returnTo)}`}><b>◎</b> 使用 ChatGPT 继续</a><div className="login-divider"><i /><span>或使用邮箱</span><i /></div>{sent ? <div className="login-sent"><b>✓</b><strong>检查你的邮箱</strong><span>登录链接已发送到 {email}，15 分钟内有效。</span><button onClick={() => setSent(false)}>换一个邮箱</button></div> : <form onSubmit={submit}><label>邮箱地址<input type="email" autoComplete="email" required value={email} onChange={(event) => setEmail(event.target.value)} placeholder="you@company.com" /></label><button disabled={busy}>{busy ? "正在发送…" : "发送登录链接"}</button></form>}{error && <div className="login-error" role="alert">{error}</div>}<small className="login-terms">继续即表示你同意 LumeWord 的服务条款和隐私政策。</small></div></section></main>;
}
